In [1]:
import csv
import pandas as pd
import numpy as np

In [2]:
white = pd.read_csv("whitemagic.csv")

In [3]:
white

      AccusedRef     CaseRef WhiteMagicRef WhiteMagic_Type
0     A/EGD/1034  C/EGD/1045      WM/JO/57      Divination
1     A/EGD/1034  C/EGD/1045      WM/JO/57      Divination
2     A/EGD/1034  C/EGD/1045      WM/JO/57      Divination
3     A/EGD/1034  C/EGD/1045      WM/JO/57      Divination
4     A/EGD/1034  C/EGD/1045      WM/JO/57      Divination
...          ...         ...           ...             ...
5578   A/JO/2954   C/JO/3093      WM/JO/64        Prophesy
5579   A/JO/2954   C/JO/3093      WM/JO/64        Prophesy
5580   A/JO/2954   C/JO/3093      WM/JO/64        Prophesy
5581   A/JO/2957   C/JO/3096      WM/JO/59      Love magic
5582   A/LA/2994   C/LA/3135      WM/LA/72      Protective

[5583 rows x 4 columns]

In [4]:
data = white.drop_duplicates(subset=['AccusedRef'], keep='first', inplace=False)
data

      AccusedRef     CaseRef WhiteMagicRef       WhiteMagic_Type
0     A/EGD/1034  C/EGD/1045      WM/JO/57            Divination
14    A/EGD/1082  C/EGD/1094      WM/LA/33            Love magic
28    A/EGD/1246  C/EGD/1258      WM/LA/16            Protective
34    A/EGD/1256  C/EGD/1268      WM/LA/18            Protective
44    A/EGD/1257  C/EGD/1269      WM/LA/19            Protective
45    A/EGD/1266  C/EGD/1278      WM/LA/22            Protective
57    A/EGD/1272  C/EGD/1284      WM/JO/32              Prophesy
67    A/EGD/1327  C/EGD/1339      WM/JO/27              Prophesy
69    A/EGD/1531  C/EGD/1545      WM/JO/67              Prophesy
71     A/EGD/161   C/EGD/172       WM/LA/1            Love magic
72    A/EGD/1753  C/EGD/1770       WM/JO/4              Prophesy
90    A/EGD/1760  C/EGD/1777      WM/LA/32         Spirit Medium
130     A/EGD/18    C/EGD/29      WM/LA/20    Finding lost goods
142   A/EGD/1854  C/EGD/1888      WM/JO/71            Protective
144   A/EGD/1955  C/EGD/1998      WM/LA/73    Finding lost goods
145   A/EGD/2066  C/EGD/2119      WM/JO/34              Prophesy
160   A/EGD/2088  C/EGD/2141      WM/JO/44            Protective
260   A/EGD/2097  C/EGD/2150      WM/JO/35            Love magic
268   A/EGD/2101  C/EGD/2154      WM/JO/42            Protective
276   A/EGD/2105  C/EGD/2158      WM/JO/58            Love magic
294   A/EGD/2108  C/EGD/2161      WM/JO/40              Prophesy
295   A/EGD/2110  C/EGD/2163      WM/JO/39              Prophesy
300   A/EGD/2117  C/EGD/2172      WM/JO/36            Protective
516   A/EGD/2151  C/EGD/2212      WM/LA/48            Divination
520   A/EGD/2191  C/EGD/2255      WM/LA/52            Protective
526   A/EGD/2192  C/EGD/2256      WM/LA/54            Divination
547   A/EGD/2193  C/EGD/2257      WM/LA/50          Second Sight
549   A/EGD/2200  C/EGD/2264      WM/LA/46            Love magic
555   A/EGD/2323  C/EGD/2394      WM/JO/65              Prophesy
556   A/EGD/2329  C/EGD/2400      WM/JO/69              Prophesy
557   A/EGD/2330  C/EGD/2401      WM/JO/66              Prophesy
558   A/EGD/2377  C/EGD/2453      WM/JO/25              Prophesy
574    A/EGD/306   C/EGD/317      WM/LA/58  Diagnose Bewitchment
581     A/EGD/48    C/EGD/59       WM/LA/6          Opening Lock
662     A/EGD/52    C/EGD/63      WM/LA/13    Finding lost goods
5342   A/EGD/586   C/EGD/597      WM/LA/70  Diagnose Bewitchment
5348   A/EGD/774   C/EGD/785      WM/LA/27              Prophesy
5453   A/EGD/779   C/EGD/790      WM/LA/28            Protective
5454    A/EGD/92   C/EGD/103      WM/LA/10    Finding lost goods
5474    A/EGD/93   C/EGD/104      WM/LA/11            Love magic
5544   A/JO/2894   C/JO/3033      WM/JO/43              Prophesy
5548   A/JO/2899   C/JO/3036      WM/JO/41            Protective
5550   A/JO/2907   C/JO/3044      WM/JO/45    Finding lost goods
5554   A/JO/2921   C/JO/3059      WM/JO/55    Finding lost goods
5578   A/JO/2954   C/JO/3093      WM/JO/64              Prophesy
5581   A/JO/2957   C/JO/3096      WM/JO/59            Love magic
5582   A/LA/2994   C/LA/3135      WM/LA/72            Protective

In [5]:
Motifs = pd.read_csv("WDB_ReligiousMotif.csv")
meetingPlaces = pd.read_csv("WDB_WitchesMeetingPlace.csv")
demonicPacts = pd.read_csv("WDB_DemonicPact.csv")
whiteMagic = pd.read_csv("WDB_WhiteMagic.csv")

accuseds = pd.read_csv("WDB_Accused.csv")
ritualObjects = pd.read_csv("WDB_RitualObject.csv")
cases = pd.read_csv("WDB_Case.csv")

In [6]:
Motifs.drop(['MotifSystemId', 'Createdby',
'MotifID', 'Createdate','MotifRef',
'Lastupdatedby', 'Lastupdatedon'], axis=1, inplace = True)
Motifs

        CaseRef  Motif_Type
0     C/JO/2882  Pilgrimage
1     C/EGD/935     Trinity
2    C/EGD/1533       Three
3     C/JO/3248       Three
4    C/EGD/1558       Three
..          ...         ...
123   C/EGD/794      Prayer
124    C/EGD/28     Trinity
125    C/EGD/28      Prayer
126    C/EGD/28   Holy well
127   C/EGD/107       Three

[128 rows x 2 columns]

In [7]:
Objects = ritualObjects[['CaseRef','RitualObject_Type']]
Objects

        CaseRef RitualObject_Type
0     C/JO/2632              Yarn
1     C/JO/2632               Egg
2     C/JO/2632              Meal
3    C/EGD/2453             Water
4     C/EGD/142           Elfshot
..          ...               ...
627   C/EGD/137            Thread
628   C/EGD/140          Hairbelt
629   C/EGD/140            Corpse
630   C/EGD/166          Camomile
631   C/EGD/147               Cat

[632 rows x 2 columns]

In [8]:
Rit_motif= pd.merge(Motifs, Objects, on = 'CaseRef')
Rit_motif

       CaseRef  Motif_Type RitualObject_Type
0    C/JO/2882  Pilgrimage             Water
1    C/JO/2882   Holy well             Water
2    C/EGD/935     Trinity             Water
3    C/EGD/935     Trinity             Shirt
4    C/EGD/935     Trinity           Bannock
..         ...         ...               ...
511   C/EGD/28   Holy well             Water
512  C/EGD/107       Three   Wax/clay images
513  C/EGD/107       Three              Toad
514  C/EGD/107       Three        Snake skin
515  C/EGD/107       Three     Urine (stale)

[516 rows x 3 columns]

In [9]:
Rit = Rit_motif['RitualObject_Type'].value_counts()
print(Rit_motif['RitualObject_Type'].value_counts())
Rit.to_csv("Rit.csv",mode='a')

Water             72
Stones            24
Shirt             24
Salt              22
Herb              20
                  ..
Hand (dead)        1
Coal               1
Flask of Water     1
Paper              1
Tether             1
Name: RitualObject_Type, Length: 97, dtype: int64

In [10]:
Motif = Rit_motif['Motif_Type'].value_counts()
print(Rit_motif['Motif_Type'].value_counts())
Motif.to_csv("Motif.csv",mode='a')

Three                140
Prayer               106
Nine                  85
Trinity               60
Saints                34
Holy well             19
Eschatology           16
Six                   13
Holy water             8
Baptising animals      7
Bible                  7
Flask of Water         5
Pilgrimage             5
Cross                  4
Angels                 3
Baptism Imagery        3
Sign of the cross      1
Name: Motif_Type, dtype: int64

In [11]:
Rit_motif.drop(['CaseRef'], axis=1, inplace = True)
Rit_motif.insert(2,'weight','')
Rit_motif.rename(columns={'Motif_Type': 'Target', 'RitualObject_Type': 'Source'}, inplace=True)
Rit_motif

         Target           Source weight
0    Pilgrimage            Water
1     Holy well            Water
2       Trinity            Water
3       Trinity            Shirt
4       Trinity          Bannock
..          ...              ...    ...
511   Holy well            Water
512       Three  Wax/clay images
513       Three             Toad
514       Three       Snake skin
515       Three    Urine (stale)

[516 rows x 3 columns]

In [12]:
demonicPacts.drop(['DemonicSystemId', 'Createdby',
'DemonicID', 'Createdate',
'Lastupdatedby', 'Lastupdatedon','DemonicRef','Demonic_Text'], axis=1, inplace = True)
demonicPacts

        CaseRef  Demonic_Type
0    C/EGD/1036       Paction
1    C/EGD/1035       Paction
2    C/EGD/1037       Paction
3     C/JO/2785       Paction
4     C/JO/2786       Paction
..          ...           ...
956   C/EGD/382           Sex
957   C/EGD/382       Servant
958   C/EGD/385  Anti-baptism
959   C/EGD/385      New name
960   C/EGD/385       Servant

[961 rows x 2 columns]

In [13]:
meetingPlaces.drop(['MeetingPlaceSystemId', 'Createdby',
'MeetingPlaceID', 'Createdate',
'Lastupdatedby', 'Lastupdatedon','MeetingPlaceRef','Location','Inversion'], axis = 1,inplace = True)

In [14]:
meetingPlaces

        CaseRef MeetingPlace_Place
0    C/EGD/1954               Yard
1     C/EGD/402                NaN
2     C/JO/2830                NaN
3     C/JO/2830                NaN
4     C/JO/2830               Burn
..          ...                ...
556   C/EGD/166              House
557   C/EGD/380              House
558   C/EGD/380                Dam
559   C/EGD/380               Road
560   C/EGD/365                Dam

[561 rows x 2 columns]

In [15]:
meeting = meetingPlaces['MeetingPlace_Place'].value_counts()
print(meetingPlaces['MeetingPlace_Place'].value_counts())
meeting.to_csv("meeting.csv",mode='a')

House             91
Yard              69
Hilltop           46
Moor              42
Burn              24
                  ..
Fish cross         1
Tolbooth           1
Bush               1
Dean bank head     1
Valley             1
Name: MeetingPlace_Place, Length: 62, dtype: int64

In [16]:
demonic = demonicPacts['Demonic_Type'].value_counts()
print(demonicPacts['Demonic_Type'].value_counts())
demonic.to_csv("demonic.csv",mode='a')

Anti-baptism             215
Devil's Mark             165
Sex                      131
Servant                  123
New name                  96
Head and foot             68
Body and soul             60
Paction                   45
Want nothing              43
Tacit pact                 4
Bond/Band                  3
sex                        2
Kisses Devil's bottom      2
tacit pact                 2
Possession                 1
Name: Demonic_Type, dtype: int64

In [17]:
Rit_meeting = pd.merge(meetingPlaces,Objects,left_on="CaseRef",right_on="CaseRef",suffixes = (False, False))
Rit_meeting

         CaseRef MeetingPlace_Place RitualObject_Type
0      C/EGD/401            Hilltop             Flesh
1      C/EGD/401                NaN             Flesh
2      C/EGD/401               Burn             Flesh
3      C/JO/2882              House             Water
4      C/JO/2882             Bridge             Water
...          ...                ...               ...
1074  C/EGD/1225            Hilltop             Shoes
1075  C/EGD/1225            Hilltop             Shirt
1076  C/EGD/1225            Hilltop       Bird (dead)
1077  C/EGD/1225            Hilltop       Hand (dead)
1078  C/EGD/1225            Hilltop             Shoes

[1079 rows x 3 columns]

In [18]:
Rit_meeting.dropna(axis=0,how='any')   # ä¸¢å¼ƒâ€˜Ageâ€™å’Œâ€˜Sexâ€™è¿™ä¸¤åˆ—ä¸­æœ‰ç¼ºå¤±å€¼çš„è¡Œ   
Rit_meeting

         CaseRef MeetingPlace_Place RitualObject_Type
0      C/EGD/401            Hilltop             Flesh
1      C/EGD/401                NaN             Flesh
2      C/EGD/401               Burn             Flesh
3      C/JO/2882              House             Water
4      C/JO/2882             Bridge             Water
...          ...                ...               ...
1074  C/EGD/1225            Hilltop             Shoes
1075  C/EGD/1225            Hilltop             Shirt
1076  C/EGD/1225            Hilltop       Bird (dead)
1077  C/EGD/1225            Hilltop       Hand (dead)
1078  C/EGD/1225            Hilltop             Shoes

[1079 rows x 3 columns]

In [19]:
Rit_meeting.drop(['CaseRef'], axis=1, inplace = True)
Rit_meeting.insert(2,'weight','')
Rit_meeting.rename(columns={'MeetingPlace_Place': 'Target', 'RitualObject_Type': 'Source'}, inplace=True)
Rit_meeting

       Target       Source weight
0     Hilltop        Flesh
1         NaN        Flesh
2        Burn        Flesh
3       House        Water
4      Bridge        Water
...       ...          ...    ...
1074  Hilltop        Shoes
1075  Hilltop        Shirt
1076  Hilltop  Bird (dead)
1077  Hilltop  Hand (dead)
1078  Hilltop        Shoes

[1079 rows x 3 columns]

In [20]:
Rit_pacts = pd.merge(demonicPacts,Objects,left_on="CaseRef",right_on="CaseRef",suffixes = (False, False))
Rit_pacts

        CaseRef   Demonic_Type RitualObject_Type
0     C/EGD/401  Body and soul             Flesh
1     C/EGD/401   Anti-baptism             Flesh
2     C/EGD/401        Servant             Flesh
3    C/EGD/1770   Devil's Mark            Tether
4    C/EGD/1770   Devil's Mark             Water
..          ...            ...               ...
649  C/EGD/1224            Sex   Wax/clay images
650  C/EGD/1225     Tacit pact             Shirt
651  C/EGD/1225     Tacit pact       Bird (dead)
652  C/EGD/1225     Tacit pact       Hand (dead)
653  C/EGD/1225     Tacit pact             Shoes

[654 rows x 3 columns]

In [21]:
Rit_pacts.drop(['CaseRef'], axis=1, inplace = True)
Rit_pacts.insert(2,'weight','')
Rit_pacts.rename(columns={'Demonic_Type': 'Target', 'RitualObject_Type': 'Source'}, inplace=True)
Rit_pacts

            Target           Source weight
0    Body and soul            Flesh
1     Anti-baptism            Flesh
2          Servant            Flesh
3     Devil's Mark           Tether
4     Devil's Mark            Water
..             ...              ...    ...
649            Sex  Wax/clay images
650     Tacit pact            Shirt
651     Tacit pact      Bird (dead)
652     Tacit pact      Hand (dead)
653     Tacit pact            Shoes

[654 rows x 3 columns]

In [22]:
Rit_motif.to_csv('Rit_motif.csv')
Rit_pacts.to_csv('Rit_pacts.csv')
Rit_meeting.to_csv('Rit_meeting.csv')